### ISSUE TITLE
--paper-date-picker-heading is applied early, requiring !important to override default styles.

### ISSUE THREAD

**Issue by josheverett** [bendavis78/paper-date-picker#160]
You've provided a mixin hook to style #heading, like so:

```css
      #heading {
        width: 168px;
        @apply(--paper-date-picker-heading);
      }
```

But styles are then defined for #heading after this @apply. So changing e.g. the padding on #heading requires the use of !important.
